### ISSUE TITLE
Feedback & Improvements

### ISSUE THREAD

**Issue by manniL** [nuxt/docs#1078]
Hey folks!

Please give feedback regarding the **documentation** of Nuxt.js in this issue.

Some things you *could* cover (but don't have to):

### Content

* What is unclear/hard to understand/could be better explained?
* What is missing in the docs?
* What is explained too verbose?
* Which examples would you like to see?
* Which parts should be structured better? How?

### Style

* Do you have problems reading the docs (font size, font style, ...)

And so on!

We'd love to hear your feedback ☺️ ❤️ 

Cross-related: https://github.com/nuxt/nuxt.js/issues/4681

---

大家好：

希望各位可以在这个Issue中提供与Nuxt.js**文档**相关的反馈。

您的评论**可以**涉及（不必包含所有）：

### 内容

* 有哪些内容不清楚或难以理解，可以如何完善？
* 文档中缺少什么内容？
* 有那些表达太冗长了？
* 您希望文档包含哪些例子？
* 哪些部分可以完善？ 有什么建议？

### 样式

* 阅读文档时遇到问题（字体大小，字体样式......）

当然也欢迎提出其他方面的想法。

我们将很期待您的反馈☺️❤️

相关Issue: https://github.com/nuxt/nuxt.js/issues/4681

**Comment by manniL** [comment]
cc @lucasfischer @sp0ken @duruld

**Comment by sp0ken** [comment]
Style is clear enough for me.

As I said in #4681, `generate mode` is often left behind. For example it is never mentionned how `asyncData` and `fetch` behave when using it. 
Debugging an error happening during the generation is also quite tricky for a lack of logging method available.

**Comment by falstack** [comment]
Hello members of the nuxt team

I found that the synchronization of nuxt's Chinese document translation is very slow and basically can't be used for reference. [Our team](https://github.com/calibur-tv) has tried both the Vue SSR's [native solution](https://github.com/calibur-tv/RhoAias) and the [nuxt solution](https://github.com/calibur-tv/Avalon). Thanks to the nuxt framework. It saves us a lot of costs. Although our products are not yet profitable, but we want to do some work for the translation of Chinese documents for nuxt, can you get your consent?

**Comment by manniL** [comment]
Hey @falstack 👋 

of course! We are happy to accept PRs to this repository which improve the Chinese docs ☺️

**Comment by mxrlkn** [comment]
I would like to see docs and examples on how to deploy nuxt as a lambda function to aws lambda, google cloud functions, netlify functions etc.

**Comment by PJLindsay** [comment]
Would like an explicit example and some minor fine tuning of the documentation of the "Cookie login flow" Vs JWT Auth flow. under local strategy here: https://auth.nuxtjs.org/reference/schemes/local

I  this area of documentation should explicitly show examples for cookie login flow Vs jwt loging flow. This would be extremely useful for newcomers to nuxt. i.e. exactly what your local strategy settings should be, such as 

// Use these settings for Cookie Auth flow
tokenRequired: false,
tokenType: false

I am afk for another day but I can make a PR tomorrow if someone doesn't want to wait

**Comment by phartikainen** [comment]
Please improve documentation / status of the module and community modules. Blog module seems to be from 2017 and apparently not working out of the box with very little documentation.

**Comment by farzadso** [comment]
@phartikainen Which part do you mean precisely? Can you please provide a link?

**Comment by phartikainen** [comment]
Official modules listed here:
https://github.com/nuxt-community/awesome-nuxt#modules

There is a blog module:
https://github.com/nuxt-community/blog-module

It does not work out of the box and it's 2 years old

**Comment by manniL** [comment]
@phartikainen Hey 👋 

`awesome-nuxt` is a community-curated resource list.

Anyway, you are right, we are cleaning up the modules soon and either update or abandon old ones 👍

**Comment by phartikainen** [comment]
Yeah I’m aware of that, but that is the only blog-related module listed

-- 
Pekka Hartikainen
www.pekkahartikainen.fi
Twitter: @pastorator

**Comment by danchristian** [comment]
I think the Nuxt documentation could do a better job at explaining when to use which mode/output for the different types of generic applications that exist. As there is SSR, SPA and then Static. You can also have an SSR application that [selectively](https://blog.lichter.io/posts/selectively-enable-ssr-or-spa-mode-in-a-nuxtjs-ap/) has SPA mode and vice versa. You can have a Static website with SPA using `generate.exclude`. You can also just have a Static website that has simple API calls to a DB aka [JAMstack](https://jamstack.org/). It can get quite confusing. 

A lot of the turorials of Nuxt are using the `generate` part to build content blogs as they are easy examples, but this maybe belittles how far you can get with the [JAMstack](https://jamstack.org/).

Google have a [helpful page](https://developers.google.com/web/updates/2019/02/rendering-on-the-web) regarding this and the Gatsby docs have a [section](https://www.gatsbyjs.org/docs/building-apps-with-gatsby/) that explains the different use cases.

I think the Nuxt documentation could be even more helpful for people coming to Nuxt for the first time. For example, here are 6 different types of website/application you might build and here is the reccomended way to build them (SPA, SSR, Static etc) and why.

**Comment by xibman** [comment]
Hi All,

It think something very unclear in the doc is how AsyncData merge data with the internal page data when you use query watcher.

Because it merge data that come from asyncData result with the original data of the page, not the current state.

**Comment by hrastnik** [comment]
I personally struggled a lot to grasp how the commands nuxt generate and nuxt build work and how their behaviour changes when the --spa flag is appended.
I am still only about 95% sure that nuxt generate --spa and nuxt build --spa produce the same output.
This only raises more questions - why does the generate command even allow the --spa flag?

The docs could explain all those modes better, also explain how does the --spa and --universal flags behave when nuxt.config.js has mode set to something different? Who wins?
Then there's the --modern flag, so that's even more things to consider.

Another thing is the errors one encounters when dealing with server side rendering and libraries that don't support it out of the box. 

I really love Nuxt and I actually believe it could be the standard for creating web apps and web sites. I just hate to think someone could stop using it because of some easily fixable error that s/he couldn't find the solution to in the docs. (almost happened to a colleague - solution was to add ssr:false to a plugin)

**Comment by codeofsumit** [comment]
I love nuxt! Thanks so much for your work on this.
I've recently started a new project so here are a few things I think are missing in the docs:

- `devModules` documentation
- `How to deploy to `now` v2: the nuxt/now-builder is not mentioned
- Deploy to ZEIT in a monorepo (not two nuxt apps, but one app with many microservices)

Thanks again for this great framework 🙏

**Comment by minijaypark** [comment]
Hi, I wonder if this is a problem, but I just found that the links in the translated documents are redirected to English one. 
For example, I was reading Routing document page in Korean (https://ko.nuxtjs.org/guide/routing/) and if I click the link to 'transition', it is connected to 'https://vuejs.org/v2/guide/transitions.html#Transitioning-Single-Elements-Components', which is original English version of transition document, even if it has Korean version.

**Comment by farzadso** [comment]
@minijaypark They're two different sites, but I think the link can be dynamic based on the language.

**Comment by richardeschloss** [comment]
Hi Nuxt team, 
First the good: really great work, it makes it fun to work with Vue. I like this framework a lot. The docs are helpful, but some minor changes I think can make it more enjoyable for the new person:
1) The sidebar used to be scroll-able (I think just a few days ago) but now it doesn't seem to be. I think it's cool that the side content grays out when the main content is in focus, however, I liked being able to scroll the sidebar. Especially on the Examples page.
2) Prev / Next buttons would be useful to go to the next chapter.

I appreciate your help. I'm still learning.

**Comment by manniL** [comment]
@richardeschloss 
Thanks for the feedback!
For your 2nd issue, there is a menu at the bottom:

![image](https://user-images.githubusercontent.com/640208/65815150-ad25a380-e1eb-11e9-8abe-2d10765f80ca.png)

**Comment by richardeschloss** [comment]
Wow that was fast! Thanks guys for doing this on a Saturday!

**Comment by ubershmekel** [comment]
Nuxt page life cycle and vue-class-component had me confused for weeks. I tried all kinds of things like like marking the data members as `!` with no default value, which caused them to not be reactive, I set the default values which caused them to be reset back to default when the route changed. I'm still not sure I have everything set up correctly. I have reactive data that is defined by the route, and when it changes, I want it to show up in the route. The simplest example is a search box that updates the URL query, and the results on the page. Here's the struggle:

```
  @Watch('$route', { immediate: true, deep: true })
  onUrlChange(to: any, from: any) {
    this.query = to.query.q;
  }

  @Watch("query")
  onQueryChanged(newQuery: string, oldQuery: string) {
    this.$router.replace({path: this.$route.path, query: { q: newQuery }});
  }
```

It's just unclear which way should the information flow and how. What I ended up doing was not modifying this.query in the route watch, but instead modifying it in the `asyncData` method using `context.route.query.q`. Because every route change would later cause the page to reset with the default values. I assumed that if I stay on the same page, all my data would stay the same - a few days in - I realized that's not the case at all and could not find any docs about it.

With all that backstory - it might make sense to describe how this kind of thing should be done. And along that it would help to see a page end-to-end life cycle diagram or list. This is what should be included as far as I'm aware:

0. `beforeRouteUpdate` is called when the route that renders this component has changed, but this component is reused in the new route, before the value of the `$route` object actually changes. Using the `beforeRouteUpdate` navigation guard, you can determine whether or not you want to prevent the route from changing or go to a different route entirely.
1. `@Watch('$route', { immediate: true, deep: true })` called when the route changes - though you have access to `this` know that your changes won't last long because the page is about to reset them.
2. `asyncData`, even if not defined - will cause all the page data members to be reset to default or the `data` method, even though the `vue` life cycle (`created`/`mounted`) is NOT called when the route changes but the page is the same.
3. `fetch`
4. if it's not the same page - `created`
5. if it's not the same page - `mounted`

**Comment by richardeschloss** [comment]
Hi Nuxt docs team, I think I can provide something helpful to: [Routing/transitions](https://nuxtjs.org/guide/routing#transitions). I got tripped up by something that *might* trip others.

I think it's great that the top of the page recommends using `<nuxt-link>` tags to switch between pages. However, I think it's important to stress that in order for page transitions to work right, `<nuxt-link>` tags (with the "to" prop set) appear to be required. I.e., using `<a>` tags and setting href will switch pages but won't trigger the animation. 

If people use bootstrap-vue, some of the examples, such as <b-nav-item>, use href, and Nuxt beginners may be tempted to copy-n-paste examples from their website and then scratch their head for awhile. Further reading on the bootstrap-vue docs reveals that the "to" prop in their components should be used instead of href.

**Comment by leesmith** [comment]
I think the deployment to [AWS w/ S3 + Cloudfront page](https://nuxtjs.org/faq/deployment-aws-s3-cloudfront) is far too complicated. If you use AWS, you'll most likely want to use the [AWS CLI](https://aws.amazon.com/cli/). Using the AWS CLI, deploying the `dist` folder to an S3 bucket AND invalidating the Cloudfront distribution is a few CLI commands. I would not follow all the gulp rigmarole as described.

Here's my `deploy.sh` that syncs the dist folder and invalidates the Cloudfront distribution: https://gist.github.com/leesmith/181dec1332a3c262f4d8a948a0afa4e1

**Comment by coreysyms** [comment]
@leesmith is ABSOLUTELY right. AWS is death by 1000 cuts anyhow, using his method is so much simpler... PRO TIP: if you're on Mac, for the love of all things holy, install AWS CLI with HomeBrew

**Comment by VesterDe** [comment]
I threw an unnecessary amount of time into subdomain auth recently. I have a subdomain that sets cookies, and auth should use those cookies on the root domain. Seemed simple enough, but I just couldn't get it to work. After going through the source, I finally found that you can give individual endpoints in the Auth module `withCredentials: true`. That did it.

`withCredentials: true` is in general important to know about when working with cookie auth etc... Perhaps mentioning it more would be good, and that it's set to true by default on some auth providers, which was what tripped me up partially, since it seemed to work out of the box when I started for one auth, then broke for one I created myself.

**Comment by codeofsumit** [comment]
Nuxt improves a lot 😍. 
At this time, I would also vote for the auth module to be the most in need of a documentation overhaul. A lot of guesswork and looking in the code happens to make it work with main providers like auth0.
Looking forward to v5 tho

**Comment by andrewmackie** [comment]
Thanks for NuxtJS.

The docs on dynamic routing are confusing.

To make dynamic routing work in SPA mode with nuxt generate, you must set generate: {fallback: true} in nuxt.config.js. This should appear as a note under the 'Unknown Dynamic Nested Routes' section. Because it's not there, people will likely go down the rabbit hole of attempting to extend the router by following the instructions in the next section (as I did).

Instead, generate: {fallback: true} is mentioned further down the page under 'SPA Fallback', where it's described (misleadingly) as a setting related only to 404s.

I would do a pull request to change it but I'm not sure how SPA Fallback section should be rewritten to make it clearer, sorry.

**Comment by debs-obrien** [comment]
Thanks so much for the feedback. @VesterDe, @codeofsumit it's next on the list so we will be improving that sorry for having to do all the guesswork lets hope our improvements makes things easier for you and everyone else. @andrewmackie yes I know, we have actually spent the last 3 months revamping our docs and they are just about to be released. as soon as they are then if things are not fully explained a pr or feedback would be great. Thanks for taking the time and hope you continue to enjoy using Nuxt.js 💚

**Comment by HappyColour** [comment]
Hello Nuxt Team . 
I'm using the NuxtJs build my company website：https://www.niu.com/ .
I think the website performance is good, because i have optimized it.
However, when i open the google pagespeed insights：https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.niu.com%2F
Wow, the score is too low on mobile especially .
I have tried too many ways but no effect . 
So, I hope you could help everyone like me .
Thx Nuxt.js Team .

**Comment by debs-obrien** [comment]
Thanks for your contributions. We are now closing this repo as docs have now moved to nuxtjs.org using content module. Please continue your contributions on that site especially focusing on the guides folder which is the new docs. Thanks

https://github.com/nuxt/nuxtjs.org/blob/master/README.md
