### ISSUE TITLE
Can `nuxtServerInit` be documented to explain its async options?

### ISSUE THREAD

**Issue by corsen2000** [nuxt/docs#39]
I did not realize until looking into the source code that `nuxtServerInit` can be async and work with promises. I think this is very helpful.

Can more information be added to the documentation?

Note: I was going to send a merge requests, but realized that this site has multiple versions of each page for language support. If it is helpful for me to send a merge request for English only, I can do so.

**Comment by alexchopin** [comment]
Hi,
We are aware about the lack of documentation and we try to complete it as much as possible.
Any help is good of course! You only need to update the english version don't worry about the other languages because we use generate option for each language.
You can only update this [file](https://github.com/nuxt/docs/blob/master/en/guide/vuex-store.md) and do a PR if you wish 👍
